# Generated by Django 6.0.7 on 2026-08-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('purchases', '0001_initial'),
        ('tresorerie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='caisse_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_achats', to='tresorerie.caisse', verbose_name='Caisse de décaissement'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='compte_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_achats', to='tresorerie.comptebancaire', verbose_name='Compte bancaire de décaissement'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='mouvement_tresorerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reception_achat', to='tresorerie.mouvementtresorerie', verbose_name='Mouvement de trésorerie associé'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='receiptcost',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='purchases.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='receiptcostallocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.product'),
        ),
        migrations.AddField(
            model_name='receiptcostallocation',
            name='receipt_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.receiptcost'),
        ),
        migrations.AddField(
            model_name='receiptcostallocation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.productvariant'),
        ),
        migrations.AddField(
            model_name='purchasepricehistory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='purchasealert',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercatalog',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercatalog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waybills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waybill',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='purchases.transporter'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptcostallocation',
            unique_together={('receipt_cost', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='purchases_p_order_n_2fe609_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchases_p_supplie_1eb951_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_date'], name='purchases_p_expecte_ad6b41_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['agence'], name='purchases_p_agence__68fe5e_idx'),
        ),
    ]
