# Generated by Django 6.0.7 on 2026-08-08 01:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        ('purchases', '0003_purchasereceiptitem_created_at'),
        ('tresorerie', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. fournisseur')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de paiement'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('invoice_type', models.CharField(choices=[('purchase', "Facture d'achat"), ('service', 'Facture de service'), ('expense', 'Facture de dépense')], default='purchase', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Fichier facture')),
                ('notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='Générée automatiquement')),
                ('is_active', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.agence', verbose_name='Agence')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.purchaseorder', verbose_name='Commande associée')),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.purchasereceipt', verbose_name='Réception associée')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchases.supplier', verbose_name='Fournisseur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.product')),
                ('receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='purchases.purchasereceiptitem')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='N° Paiement')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='Reçu')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.agence')),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tresorerie.caisse', verbose_name='Caisse utilisée')),
                ('compte_bancaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tresorerie.comptebancaire', verbose_name='Compte bancaire utilisé')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.invoice', verbose_name='Facture')),
                ('mouvement_tresorerie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='tresorerie.mouvementtresorerie', verbose_name='Mouvement de trésorerie')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-payment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='purchases_i_invoice_4b45d2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['supplier', 'status'], name='purchases_i_supplie_8f0730_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='purchases_i_due_dat_c3c326_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agence'], name='purchases_i_agence__1e5e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='purchases_p_payment_628e51_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='purchases_p_invoice_6c51f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='purchases_p_payment_8b2428_idx'),
        ),
    ]
