# Generated by Django 6.0.7 on 2026-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_invoiceitem_options_invoiceitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant restant'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Taux de change'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('purchase', "Facture d'achat"), ('service', 'Facture de service'), ('expense', 'Facture de dépense')], default='purchase', max_length=20, verbose_name='Type de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de paiement'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
    ]
