# Generated by Django 6.0.7 on 2026-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_invoiceitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='auto_invoice',
            field=models.BooleanField(default=True, verbose_name='Créer facture automatiquement'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='auto_invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Facture auto'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='Facturée'),
        ),
    ]
