# Generated by Django 6.0.7 on 2026-08-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('purchases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecomptable',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_comptables', to='purchases.purchaseorder', verbose_name='Achat'),
        ),
        migrations.AddField(
            model_name='facturecomptable',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_comptables', to='users.agence', verbose_name='Agence'),
        ),
    ]
