# Generated by Django 6.0.7 on 2026-08-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0002_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecomptable',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_comptables', to='sales.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='facturecomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_comptables_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='facturecomptable',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_comptables', to='purchases.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='facturecomptable',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_comptables', to='sales.vente', verbose_name='Vente'),
        ),
        migrations.AddField(
            model_name='indicateurfinancier',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='journal',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journaux', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='ecriture',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.journal', verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='lignebalance',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.balance', verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='ecriture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriture', verbose_name='Écriture'),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancomptable',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='comptabilite.plancomptable', verbose_name='Compte parent'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='comptabilite.plancomptable', verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='lignebalance',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_balance', to='comptabilite.plancomptable', verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements', to='sales.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements', to='comptabilite.facturecomptable', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglements', to='purchases.supplier', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='soldecompte',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldes_comptes', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='soldecompte',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldes', to='comptabilite.plancomptable', verbose_name='Compte'),
        ),
        migrations.AlterUniqueTogether(
            name='cloturecomptable',
            unique_together={('agence', 'date_debut', 'date_fin')},
        ),
        migrations.AddIndex(
            model_name='facturecomptable',
            index=models.Index(fields=['reference'], name='comptabilit_referen_77fdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='facturecomptable',
            index=models.Index(fields=['type_facture', 'status'], name='comptabilit_type_fa_b87357_idx'),
        ),
        migrations.AddIndex(
            model_name='facturecomptable',
            index=models.Index(fields=['date_facture', 'date_echeance'], name='comptabilit_date_fa_42d900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('agence', 'code')},
        ),
        migrations.AddIndex(
            model_name='ecriture',
            index=models.Index(fields=['reference'], name='comptabilit_referen_d7c75f_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriture',
            index=models.Index(fields=['date_ecriture'], name='comptabilit_date_ec_232d64_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriture',
            index=models.Index(fields=['journal', 'status'], name='comptabilit_journal_2d917a_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriture',
            index=models.Index(fields=['agence', 'date_ecriture'], name='comptabilit_agence__9699e4_idx'),
        ),
        migrations.AddIndex(
            model_name='reglement',
            index=models.Index(fields=['reference'], name='comptabilit_referen_c2993d_idx'),
        ),
        migrations.AddIndex(
            model_name='reglement',
            index=models.Index(fields=['type_reglement', 'date_reglement'], name='comptabilit_type_re_86d439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soldecompte',
            unique_together={('compte', 'agence', 'date_solde')},
        ),
    ]
