# Generated by Django 6.0.7 on 2026-08-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaire', '0002_initial'),
        ('produits', '0001_initial'),
        ('sales', '0001_initial'),
        ('tresorerie', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='caisse_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_entrants_sales', to='tresorerie.caisse', verbose_name='Caisse de destination'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='sales.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='compte_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_entrants_sales', to='tresorerie.comptebancaire', verbose_name='Compte bancaire de destination'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='encaisse_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='sales.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mouvement_tresorerie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_sale', to='tresorerie.mouvementtresorerie', verbose_name='Mouvement de trésorerie associé'),
        ),
        migrations.AddField(
            model_name='vente',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='users.agence'),
        ),
        migrations.AddField(
            model_name='vente',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ventes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='sales.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='sales.vente'),
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='sales.vente'),
        ),
        migrations.AddField(
            model_name='venteitem',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lot prélevé pour cette ligne (si sélection manuelle)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_items', to='inventaire.lot'),
        ),
        migrations.AddField(
            model_name='venteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.product'),
        ),
        migrations.AddField(
            model_name='venteitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.productvariant'),
        ),
        migrations.AddField(
            model_name='venteitem',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.vente'),
        ),
        migrations.AddField(
            model_name='venteitem',
            name='warehouse_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaire.warehouse'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['reference'], name='sales_devis_referen_bdbd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['status'], name='sales_devis_status_0d687e_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['agence', 'status'], name='sales_devis_agence__a92eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['reference'], name='sales_vente_referen_6680ea_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['status'], name='sales_vente_status_f1cf47_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['agence', 'status'], name='sales_vente_agence__a1b4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference'], name='sales_paiem_referen_68abef_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture', 'statut'], name='sales_paiem_facture_f90798_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='sales_paiem_date_pa_38f5ef_idx'),
        ),
    ]
