# Generated by Django 6.0.7 on 2026-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementtresorerie',
            name='source_type',
            field=models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat'), ('facture_client', 'Facture client'), ('facture_fournisseur', 'Facture fournisseur'), ('reglement', 'Règlement'), ('ecriture', 'Écriture comptable'), ('salaire', 'Salaire'), ('frais', 'Frais'), ('payment', 'Paiement fournisseur'), ('caisse', 'Caisse'), ('compte_bancaire', 'Compte bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Type source'),
        ),
    ]
